// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webhooks.proto

package io.tradle.joe.protocols;

public final class WebHookProtos {
  private WebHookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code webhooks.Event}
   */
  public enum Event
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>KeyValue = 1;</code>
     */
    KeyValue(0, 1),
    /**
     * <code>Rewind = 2;</code>
     */
    Rewind(1, 2),
    ;

    /**
     * <code>KeyValue = 1;</code>
     */
    public static final int KeyValue_VALUE = 1;
    /**
     * <code>Rewind = 2;</code>
     */
    public static final int Rewind_VALUE = 2;


    public final int getNumber() { return value; }

    public static Event valueOf(int value) {
      switch (value) {
        case 1: return KeyValue;
        case 2: return Rewind;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Event>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Event>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Event>() {
            public Event findValueByNumber(int number) {
              return Event.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.tradle.joe.protocols.WebHookProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Event[] VALUES = values();

    public static Event valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Event(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:webhooks.Event)
  }

  public interface WebHookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webhooks.WebHook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string url = 1;</code>
     */
    boolean hasUrl();
    /**
     * <code>required string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>required string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>required .webhooks.Event event = 2;</code>
     */
    boolean hasEvent();
    /**
     * <code>required .webhooks.Event event = 2;</code>
     */
    io.tradle.joe.protocols.WebHookProtos.Event getEvent();

    /**
     * <code>optional int32 timeoutsCount = 3;</code>
     */
    boolean hasTimeoutsCount();
    /**
     * <code>optional int32 timeoutsCount = 3;</code>
     */
    int getTimeoutsCount();

    /**
     * <code>optional bool unlimitedTimeouts = 4;</code>
     */
    boolean hasUnlimitedTimeouts();
    /**
     * <code>optional bool unlimitedTimeouts = 4;</code>
     */
    boolean getUnlimitedTimeouts();
  }
  /**
   * Protobuf type {@code webhooks.WebHook}
   */
  public static final class WebHook extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webhooks.WebHook)
      WebHookOrBuilder {
    // Use WebHook.newBuilder() to construct.
    private WebHook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WebHook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WebHook defaultInstance;
    public static WebHook getDefaultInstance() {
      return defaultInstance;
    }

    public WebHook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WebHook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              url_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              io.tradle.joe.protocols.WebHookProtos.Event value = io.tradle.joe.protocols.WebHookProtos.Event.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                event_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeoutsCount_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              unlimitedTimeouts_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.tradle.joe.protocols.WebHookProtos.WebHook.class, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder.class);
    }

    public static com.google.protobuf.Parser<WebHook> PARSER =
        new com.google.protobuf.AbstractParser<WebHook>() {
      public WebHook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebHook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WebHook> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    /**
     * <code>required string url = 1;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_FIELD_NUMBER = 2;
    private io.tradle.joe.protocols.WebHookProtos.Event event_;
    /**
     * <code>required .webhooks.Event event = 2;</code>
     */
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .webhooks.Event event = 2;</code>
     */
    public io.tradle.joe.protocols.WebHookProtos.Event getEvent() {
      return event_;
    }

    public static final int TIMEOUTSCOUNT_FIELD_NUMBER = 3;
    private int timeoutsCount_;
    /**
     * <code>optional int32 timeoutsCount = 3;</code>
     */
    public boolean hasTimeoutsCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 timeoutsCount = 3;</code>
     */
    public int getTimeoutsCount() {
      return timeoutsCount_;
    }

    public static final int UNLIMITEDTIMEOUTS_FIELD_NUMBER = 4;
    private boolean unlimitedTimeouts_;
    /**
     * <code>optional bool unlimitedTimeouts = 4;</code>
     */
    public boolean hasUnlimitedTimeouts() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool unlimitedTimeouts = 4;</code>
     */
    public boolean getUnlimitedTimeouts() {
      return unlimitedTimeouts_;
    }

    private void initFields() {
      url_ = "";
      event_ = io.tradle.joe.protocols.WebHookProtos.Event.KeyValue;
      timeoutsCount_ = 0;
      unlimitedTimeouts_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEvent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, event_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, timeoutsCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, unlimitedTimeouts_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, event_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, timeoutsCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, unlimitedTimeouts_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.tradle.joe.protocols.WebHookProtos.WebHook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webhooks.WebHook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webhooks.WebHook)
        io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.tradle.joe.protocols.WebHookProtos.WebHook.class, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder.class);
      }

      // Construct using io.tradle.joe.protocols.WebHookProtos.WebHook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        event_ = io.tradle.joe.protocols.WebHookProtos.Event.KeyValue;
        bitField0_ = (bitField0_ & ~0x00000002);
        timeoutsCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        unlimitedTimeouts_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHook_descriptor;
      }

      public io.tradle.joe.protocols.WebHookProtos.WebHook getDefaultInstanceForType() {
        return io.tradle.joe.protocols.WebHookProtos.WebHook.getDefaultInstance();
      }

      public io.tradle.joe.protocols.WebHookProtos.WebHook build() {
        io.tradle.joe.protocols.WebHookProtos.WebHook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.tradle.joe.protocols.WebHookProtos.WebHook buildPartial() {
        io.tradle.joe.protocols.WebHookProtos.WebHook result = new io.tradle.joe.protocols.WebHookProtos.WebHook(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.event_ = event_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeoutsCount_ = timeoutsCount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.unlimitedTimeouts_ = unlimitedTimeouts_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.tradle.joe.protocols.WebHookProtos.WebHook) {
          return mergeFrom((io.tradle.joe.protocols.WebHookProtos.WebHook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.tradle.joe.protocols.WebHookProtos.WebHook other) {
        if (other == io.tradle.joe.protocols.WebHookProtos.WebHook.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          bitField0_ |= 0x00000001;
          url_ = other.url_;
          onChanged();
        }
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (other.hasTimeoutsCount()) {
          setTimeoutsCount(other.getTimeoutsCount());
        }
        if (other.hasUnlimitedTimeouts()) {
          setUnlimitedTimeouts(other.getUnlimitedTimeouts());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasEvent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.tradle.joe.protocols.WebHookProtos.WebHook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.tradle.joe.protocols.WebHookProtos.WebHook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object url_ = "";
      /**
       * <code>required string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>required string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }

      private io.tradle.joe.protocols.WebHookProtos.Event event_ = io.tradle.joe.protocols.WebHookProtos.Event.KeyValue;
      /**
       * <code>required .webhooks.Event event = 2;</code>
       */
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .webhooks.Event event = 2;</code>
       */
      public io.tradle.joe.protocols.WebHookProtos.Event getEvent() {
        return event_;
      }
      /**
       * <code>required .webhooks.Event event = 2;</code>
       */
      public Builder setEvent(io.tradle.joe.protocols.WebHookProtos.Event value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .webhooks.Event event = 2;</code>
       */
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        event_ = io.tradle.joe.protocols.WebHookProtos.Event.KeyValue;
        onChanged();
        return this;
      }

      private int timeoutsCount_ ;
      /**
       * <code>optional int32 timeoutsCount = 3;</code>
       */
      public boolean hasTimeoutsCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 timeoutsCount = 3;</code>
       */
      public int getTimeoutsCount() {
        return timeoutsCount_;
      }
      /**
       * <code>optional int32 timeoutsCount = 3;</code>
       */
      public Builder setTimeoutsCount(int value) {
        bitField0_ |= 0x00000004;
        timeoutsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeoutsCount = 3;</code>
       */
      public Builder clearTimeoutsCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeoutsCount_ = 0;
        onChanged();
        return this;
      }

      private boolean unlimitedTimeouts_ ;
      /**
       * <code>optional bool unlimitedTimeouts = 4;</code>
       */
      public boolean hasUnlimitedTimeouts() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool unlimitedTimeouts = 4;</code>
       */
      public boolean getUnlimitedTimeouts() {
        return unlimitedTimeouts_;
      }
      /**
       * <code>optional bool unlimitedTimeouts = 4;</code>
       */
      public Builder setUnlimitedTimeouts(boolean value) {
        bitField0_ |= 0x00000008;
        unlimitedTimeouts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool unlimitedTimeouts = 4;</code>
       */
      public Builder clearUnlimitedTimeouts() {
        bitField0_ = (bitField0_ & ~0x00000008);
        unlimitedTimeouts_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:webhooks.WebHook)
    }

    static {
      defaultInstance = new WebHook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:webhooks.WebHook)
  }

  public interface WebHooksOrBuilder extends
      // @@protoc_insertion_point(interface_extends:webhooks.WebHooks)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    java.util.List<io.tradle.joe.protocols.WebHookProtos.WebHook> 
        getWebHooksList();
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    io.tradle.joe.protocols.WebHookProtos.WebHook getWebHooks(int index);
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    int getWebHooksCount();
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    java.util.List<? extends io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder> 
        getWebHooksOrBuilderList();
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder getWebHooksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code webhooks.WebHooks}
   */
  public static final class WebHooks extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:webhooks.WebHooks)
      WebHooksOrBuilder {
    // Use WebHooks.newBuilder() to construct.
    private WebHooks(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WebHooks(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WebHooks defaultInstance;
    public static WebHooks getDefaultInstance() {
      return defaultInstance;
    }

    public WebHooks getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WebHooks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                webHooks_ = new java.util.ArrayList<io.tradle.joe.protocols.WebHookProtos.WebHook>();
                mutable_bitField0_ |= 0x00000001;
              }
              webHooks_.add(input.readMessage(io.tradle.joe.protocols.WebHookProtos.WebHook.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          webHooks_ = java.util.Collections.unmodifiableList(webHooks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHooks_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHooks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.tradle.joe.protocols.WebHookProtos.WebHooks.class, io.tradle.joe.protocols.WebHookProtos.WebHooks.Builder.class);
    }

    public static com.google.protobuf.Parser<WebHooks> PARSER =
        new com.google.protobuf.AbstractParser<WebHooks>() {
      public WebHooks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebHooks(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WebHooks> getParserForType() {
      return PARSER;
    }

    public static final int WEBHOOKS_FIELD_NUMBER = 1;
    private java.util.List<io.tradle.joe.protocols.WebHookProtos.WebHook> webHooks_;
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    public java.util.List<io.tradle.joe.protocols.WebHookProtos.WebHook> getWebHooksList() {
      return webHooks_;
    }
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    public java.util.List<? extends io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder> 
        getWebHooksOrBuilderList() {
      return webHooks_;
    }
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    public int getWebHooksCount() {
      return webHooks_.size();
    }
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    public io.tradle.joe.protocols.WebHookProtos.WebHook getWebHooks(int index) {
      return webHooks_.get(index);
    }
    /**
     * <code>repeated .webhooks.WebHook webHooks = 1;</code>
     */
    public io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder getWebHooksOrBuilder(
        int index) {
      return webHooks_.get(index);
    }

    private void initFields() {
      webHooks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getWebHooksCount(); i++) {
        if (!getWebHooks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < webHooks_.size(); i++) {
        output.writeMessage(1, webHooks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < webHooks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, webHooks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.tradle.joe.protocols.WebHookProtos.WebHooks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.tradle.joe.protocols.WebHookProtos.WebHooks prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code webhooks.WebHooks}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:webhooks.WebHooks)
        io.tradle.joe.protocols.WebHookProtos.WebHooksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHooks_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHooks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.tradle.joe.protocols.WebHookProtos.WebHooks.class, io.tradle.joe.protocols.WebHookProtos.WebHooks.Builder.class);
      }

      // Construct using io.tradle.joe.protocols.WebHookProtos.WebHooks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWebHooksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (webHooksBuilder_ == null) {
          webHooks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          webHooksBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.tradle.joe.protocols.WebHookProtos.internal_static_webhooks_WebHooks_descriptor;
      }

      public io.tradle.joe.protocols.WebHookProtos.WebHooks getDefaultInstanceForType() {
        return io.tradle.joe.protocols.WebHookProtos.WebHooks.getDefaultInstance();
      }

      public io.tradle.joe.protocols.WebHookProtos.WebHooks build() {
        io.tradle.joe.protocols.WebHookProtos.WebHooks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.tradle.joe.protocols.WebHookProtos.WebHooks buildPartial() {
        io.tradle.joe.protocols.WebHookProtos.WebHooks result = new io.tradle.joe.protocols.WebHookProtos.WebHooks(this);
        int from_bitField0_ = bitField0_;
        if (webHooksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            webHooks_ = java.util.Collections.unmodifiableList(webHooks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.webHooks_ = webHooks_;
        } else {
          result.webHooks_ = webHooksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.tradle.joe.protocols.WebHookProtos.WebHooks) {
          return mergeFrom((io.tradle.joe.protocols.WebHookProtos.WebHooks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.tradle.joe.protocols.WebHookProtos.WebHooks other) {
        if (other == io.tradle.joe.protocols.WebHookProtos.WebHooks.getDefaultInstance()) return this;
        if (webHooksBuilder_ == null) {
          if (!other.webHooks_.isEmpty()) {
            if (webHooks_.isEmpty()) {
              webHooks_ = other.webHooks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWebHooksIsMutable();
              webHooks_.addAll(other.webHooks_);
            }
            onChanged();
          }
        } else {
          if (!other.webHooks_.isEmpty()) {
            if (webHooksBuilder_.isEmpty()) {
              webHooksBuilder_.dispose();
              webHooksBuilder_ = null;
              webHooks_ = other.webHooks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              webHooksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWebHooksFieldBuilder() : null;
            } else {
              webHooksBuilder_.addAllMessages(other.webHooks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getWebHooksCount(); i++) {
          if (!getWebHooks(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.tradle.joe.protocols.WebHookProtos.WebHooks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.tradle.joe.protocols.WebHookProtos.WebHooks) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.tradle.joe.protocols.WebHookProtos.WebHook> webHooks_ =
        java.util.Collections.emptyList();
      private void ensureWebHooksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          webHooks_ = new java.util.ArrayList<io.tradle.joe.protocols.WebHookProtos.WebHook>(webHooks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          io.tradle.joe.protocols.WebHookProtos.WebHook, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder, io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder> webHooksBuilder_;

      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public java.util.List<io.tradle.joe.protocols.WebHookProtos.WebHook> getWebHooksList() {
        if (webHooksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(webHooks_);
        } else {
          return webHooksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public int getWebHooksCount() {
        if (webHooksBuilder_ == null) {
          return webHooks_.size();
        } else {
          return webHooksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public io.tradle.joe.protocols.WebHookProtos.WebHook getWebHooks(int index) {
        if (webHooksBuilder_ == null) {
          return webHooks_.get(index);
        } else {
          return webHooksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder setWebHooks(
          int index, io.tradle.joe.protocols.WebHookProtos.WebHook value) {
        if (webHooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWebHooksIsMutable();
          webHooks_.set(index, value);
          onChanged();
        } else {
          webHooksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder setWebHooks(
          int index, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder builderForValue) {
        if (webHooksBuilder_ == null) {
          ensureWebHooksIsMutable();
          webHooks_.set(index, builderForValue.build());
          onChanged();
        } else {
          webHooksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder addWebHooks(io.tradle.joe.protocols.WebHookProtos.WebHook value) {
        if (webHooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWebHooksIsMutable();
          webHooks_.add(value);
          onChanged();
        } else {
          webHooksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder addWebHooks(
          int index, io.tradle.joe.protocols.WebHookProtos.WebHook value) {
        if (webHooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWebHooksIsMutable();
          webHooks_.add(index, value);
          onChanged();
        } else {
          webHooksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder addWebHooks(
          io.tradle.joe.protocols.WebHookProtos.WebHook.Builder builderForValue) {
        if (webHooksBuilder_ == null) {
          ensureWebHooksIsMutable();
          webHooks_.add(builderForValue.build());
          onChanged();
        } else {
          webHooksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder addWebHooks(
          int index, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder builderForValue) {
        if (webHooksBuilder_ == null) {
          ensureWebHooksIsMutable();
          webHooks_.add(index, builderForValue.build());
          onChanged();
        } else {
          webHooksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder addAllWebHooks(
          java.lang.Iterable<? extends io.tradle.joe.protocols.WebHookProtos.WebHook> values) {
        if (webHooksBuilder_ == null) {
          ensureWebHooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, webHooks_);
          onChanged();
        } else {
          webHooksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder clearWebHooks() {
        if (webHooksBuilder_ == null) {
          webHooks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          webHooksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public Builder removeWebHooks(int index) {
        if (webHooksBuilder_ == null) {
          ensureWebHooksIsMutable();
          webHooks_.remove(index);
          onChanged();
        } else {
          webHooksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public io.tradle.joe.protocols.WebHookProtos.WebHook.Builder getWebHooksBuilder(
          int index) {
        return getWebHooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder getWebHooksOrBuilder(
          int index) {
        if (webHooksBuilder_ == null) {
          return webHooks_.get(index);  } else {
          return webHooksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public java.util.List<? extends io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder> 
           getWebHooksOrBuilderList() {
        if (webHooksBuilder_ != null) {
          return webHooksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(webHooks_);
        }
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public io.tradle.joe.protocols.WebHookProtos.WebHook.Builder addWebHooksBuilder() {
        return getWebHooksFieldBuilder().addBuilder(
            io.tradle.joe.protocols.WebHookProtos.WebHook.getDefaultInstance());
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public io.tradle.joe.protocols.WebHookProtos.WebHook.Builder addWebHooksBuilder(
          int index) {
        return getWebHooksFieldBuilder().addBuilder(
            index, io.tradle.joe.protocols.WebHookProtos.WebHook.getDefaultInstance());
      }
      /**
       * <code>repeated .webhooks.WebHook webHooks = 1;</code>
       */
      public java.util.List<io.tradle.joe.protocols.WebHookProtos.WebHook.Builder> 
           getWebHooksBuilderList() {
        return getWebHooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          io.tradle.joe.protocols.WebHookProtos.WebHook, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder, io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder> 
          getWebHooksFieldBuilder() {
        if (webHooksBuilder_ == null) {
          webHooksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              io.tradle.joe.protocols.WebHookProtos.WebHook, io.tradle.joe.protocols.WebHookProtos.WebHook.Builder, io.tradle.joe.protocols.WebHookProtos.WebHookOrBuilder>(
                  webHooks_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          webHooks_ = null;
        }
        return webHooksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:webhooks.WebHooks)
    }

    static {
      defaultInstance = new WebHooks(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:webhooks.WebHooks)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webhooks_WebHook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webhooks_WebHook_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webhooks_WebHooks_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webhooks_WebHooks_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016webhooks.proto\022\010webhooks\"h\n\007WebHook\022\013\n" +
      "\003url\030\001 \002(\t\022\036\n\005event\030\002 \002(\0162\017.webhooks.Eve" +
      "nt\022\025\n\rtimeoutsCount\030\003 \001(\005\022\031\n\021unlimitedTi" +
      "meouts\030\004 \001(\010\"/\n\010WebHooks\022#\n\010webHooks\030\001 \003" +
      "(\0132\021.webhooks.WebHook*!\n\005Event\022\014\n\010KeyVal" +
      "ue\020\001\022\n\n\006Rewind\020\002B(\n\027io.tradle.joe.protoc" +
      "olsB\rWebHookProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_webhooks_WebHook_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webhooks_WebHook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webhooks_WebHook_descriptor,
        new java.lang.String[] { "Url", "Event", "TimeoutsCount", "UnlimitedTimeouts", });
    internal_static_webhooks_WebHooks_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webhooks_WebHooks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webhooks_WebHooks_descriptor,
        new java.lang.String[] { "WebHooks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
